<?php

/**
 * SdFlujoAccion
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-11-07, 14:17:41
 */
class SdFlujoAccion extends \Phalcon\Mvc\Model
{
    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(column="ID", type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var integer
     * @Column(column="ID_FLUJO", type="integer", length=11, nullable=false)
     */
    public $id_flujo;

    /**
     *
     * @var string
     * @Column(column="NOMBRE", type="string", length=255, nullable=false)
     */
    public $nombre;

    /**
     *
     * @var string
     * @Column(column="DESCRIPCION", type="string", length=255, nullable=false)
     */
    public $descripcion;

    /**
     *
     * @var string
     * @Column(column="TIPO", type="string", length=255, nullable=true)
     */
    public $tipo;

    /**
     *
     * @var string
     * @Column(column="TABLA", type="string", length=255, nullable=true)
     */
    public $tabla;

    /**
     *
     * @var string
     * @Column(column="CAMPO", type="string", length=255, nullable=true)
     */
    public $campo;

    /**
     *
     * @var string
     * @Column(column="VALOR", type="string", length=255, nullable=true)
     */
    public $valor;

    /**
     *
     * @var string
     * @Column(column="N_ESTADO", type="string", length=255, nullable=true)
     */
    public $n_estado;

    /**
     *
     * @var string
     * @Column(column="N_ETAPA", type="string", length=255, nullable=true)
     */
    public $n_etapa;

    /**
     *
     * @var string
     * @Column(column="USUARIO_I", type="string", length=20, nullable=false)
     */
    public $usuario_i;

    /**
     *
     * @var string
     * @Column(column="FECHA_I", type="string", nullable=false)
     */
    public $fecha_i;

    /**
     *
     * @var string
     * @Column(column="USUARIO_U", type="string", length=20, nullable=false)
     */
    public $usuario_u;

    /**
     *
     * @var string
     * @Column(column="FECHA_U", type="string", nullable=false)
     */
    public $fecha_u;

    /**
     *
     * @var string
     * @Column(column="ESTATUS", type="string", length=5, nullable=false)
     */
    public $estatus;

    /**
     *
     * @var integer
     * @Column(column="N_ESTADO_ID", type="integer", length=11, nullable=true)
     */
    public $n_estado_id;

    /**
     *
     * @var integer
     * @Column(column="N_ETAPA_ID", type="integer", length=11, nullable=true)
     */
    public $n_etapa_id;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("MGR_SAIDA");
        $this->setSource("sd_flujo_accion");
        $this->hasMany('ID', 'SdFlujoTransaccionAccion', 'ID_ACCION', ['alias' => 'SdFlujoTransaccionAccion']);
        $this->belongsTo('ID_FLUJO', '\SdFlujo', 'ID_FLUJO', ['alias' => 'SdFlujo']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'sd_flujo_accion';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return SdFlujoAccion[]|SdFlujoAccion|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return SdFlujoAccion|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return [
            'ID' => 'id',
            'ID_FLUJO' => 'id_flujo',
            'NOMBRE' => 'nombre',
            'DESCRIPCION' => 'descripcion',
            'TIPO' => 'tipo',
            'TABLA' => 'tabla',
            'CAMPO' => 'campo',
            'VALOR' => 'valor',
            'N_ESTADO' => 'n_estado',
            'N_ETAPA' => 'n_etapa',
            'USUARIO_I' => 'usuario_i',
            'FECHA_I' => 'fecha_i',
            'USUARIO_U' => 'usuario_u',
            'FECHA_U' => 'fecha_u',
            'ESTATUS' => 'estatus',
            'N_ESTADO_ID' => 'n_estado_id',
            'N_ETAPA_ID' => 'n_etapa_id'
        ];
    }
}